

#include "ConstDataBP.h"
#include "CampType.h"
#include "GameDefine.h"
#include"Chuangshi.h"

UConstDataBP::UConstDataBP()
{
	///阵营关系
	CAMP_RELATION_MAP.Add(FString::Printf(TEXT("%i_%i"), static_cast<int>(CAMP_TYPE_ENUM::CAMP_TAOISM), static_cast<int>(CAMP_TYPE_ENUM::CAMP_DEMON)), COMBAT_RELATION::COMBAT_RELATION_ENEMY);				///仙&魔
	CAMP_RELATION_MAP.Add(FString::Printf(TEXT("%i_%i"), static_cast<int>(CAMP_TYPE_ENUM::CAMP_TAOISM), static_cast<int>(CAMP_TYPE_ENUM::CAMP_NEUTRAL_ENEMY)), COMBAT_RELATION::COMBAT_RELATION_ENEMY);		///仙&中立敌对
	CAMP_RELATION_MAP.Add(FString::Printf(TEXT("%i_%i"), static_cast<int>(CAMP_TYPE_ENUM::CAMP_TAOISM), static_cast<int>(CAMP_TYPE_ENUM::CAMP_NEUTRAL_NORMAL)), COMBAT_RELATION::COMBAT_RELATION_NORMAL);	///仙&中立友好
	CAMP_RELATION_MAP.Add(FString::Printf(TEXT("%i_%i"), static_cast<int>(CAMP_TYPE_ENUM::CAMP_DEMON), static_cast<int>(CAMP_TYPE_ENUM::CAMP_NEUTRAL_ENEMY)), COMBAT_RELATION::COMBAT_RELATION_ENEMY);		///魔&中立敌对
	CAMP_RELATION_MAP.Add(FString::Printf(TEXT("%i_%i"), static_cast<int>(CAMP_TYPE_ENUM::CAMP_DEMON), static_cast<int>(CAMP_TYPE_ENUM::CAMP_NEUTRAL_NORMAL)), COMBAT_RELATION::COMBAT_RELATION_NORMAL);	///魔&中立友好
	CAMP_RELATION_MAP.Add(FString::Printf(TEXT("%i_%i"), static_cast<int>(CAMP_TYPE_ENUM::CAMP_NEUTRAL_ENEMY), static_cast<int>(CAMP_TYPE_ENUM::CAMP_NEUTRAL_NORMAL)), COMBAT_RELATION::COMBAT_RELATION_NORMAL);///中立敌对&中立友好

	///玩家关系规则与关系判断类的对应关系
	ROLE_RELATION_RULE_TO_REL_CLS.Add(ROLE_RELATION_RULE::RELATION_RULE_CAMP, "RelRole_Camp");
	ROLE_RELATION_RULE_TO_REL_CLS.Add(ROLE_RELATION_RULE::RELATION_RULE_PKMODE, "RelRole_PKMode");
	ROLE_RELATION_RULE_TO_REL_CLS.Add(ROLE_RELATION_RULE::RELATION_RULE_PEACE, "RelRole_Peace");
	ROLE_RELATION_RULE_TO_REL_CLS.Add(ROLE_RELATION_RULE::ROLE_RELATION_RULE_ENEMY, "RelRole_Enemy");
	ROLE_RELATION_RULE_TO_REL_CLS.Add(ROLE_RELATION_RULE::ROLE_RELATION_RULE_TONG_STARCRAFT, "RelRole_TongStarcraft");
	ROLE_RELATION_RULE_TO_REL_CLS.Add(ROLE_RELATION_RULE::ROLE_RELATION_RULE_TEAM_STARCRAFT, "RelRole_TeamStarcraft");
	ROLE_RELATION_RULE_TO_REL_CLS.Add(ROLE_RELATION_RULE::ROLE_RELATION_RULE_BLONG_SIDE, "RelRoleEntityRelationGCZ");
	ROLE_RELATION_RULE_TO_REL_CLS.Add(ROLE_RELATION_RULE::ROLE_RELATION_RULE_BLONG_SIDE, "RelRoleEntityRelationGCZ");
	ROLE_RELATION_RULE_TO_REL_CLS.Add(ROLE_RELATION_RULE::ROLE_RELATION_RULE_LHMJ, "RelRoleEntityRelationLHMJ");
}

 UConstDataBP* UConstDataBP::GetInstance()
 {
	 cs3_checkNoReentry();

	return NewObject<UConstDataBP>();
}