#pragma once

/**
* 文件名称：EnumCsvDefine.h
* 功能说明：
* 文件作者：xiushuang
* 目前维护：all
* 创建时间：2016-08-29
*/

///各配置表的类型
UENUM()
enum class CSV_CONFIG_TYPE_ENUM :uint16
{
	///空
	CSV_CONFIG_TYPE_NULL = 0	UMETA(DisplayName = "CSV_CONFIG_TYPE_NULL"),
	///模型配置表
	CSV_CONFIG_TYPE_MODEL = 101 UMETA(DisplayName = "CSV_CONFIG_TYPE_MODEL"),
	///模型配置表
	CSV_CONFIG_ROLE_CREATE = 102 UMETA(DisplayName = "CSV_CONFIG_ROLE_CREATE_UI"),
	///部件配置表
	CSV_CONFIG_TYPE_PART_MODEL = 103 UMETA(DisplayName = "CSV_CONFIG_TYPE_PART_MODEL"),
	///模型部件变色
	CSV_CONFIG_TYPE_MODEL_SCHEME = 104 UMETA(DisplayName = "CSV_CONFIG_TYPE_MODEL_SCHEME"),
	///粒子配置表
	CSV_CONFIG_TYPE_PARTICLE = 105 UMETA(DisplayName = "CSV_CONFIG_TYPE_PARTICLE"),
	///剧情配置表
	CSV_CONFIG_TYPE_STORY = 107 UMETA(DisplayName = "CSV_CONFIG_TYPE_STORY"),
	///剧情预加载配置表
	CSV_CONFIG_TYPE_PRELOADSTORY = 109 UMETA(DisplayName = "CSV_CONFIG_TYPE_PRELOADSTORY"),
	///界面配置表
	CSV_CONFIG_TYPE_UI = 111 UMETA(DisplayName = "CSV_CONFIG_TYPE_UI"),
	///提示消息配置表
	CSV_CONFIG_TYPE_MESSAGE = 113 UMETA(DisplayName = "CSV_CONFIG_TYPE_MESSAGE"),
	///技能数据配置表
	CSV_CONFIG_TYPE_SKILL = 115 UMETA(DisplayName = "CSV_CONFIG_TYPE_SKILL"),
	///被动技能数据配置表
	CSV_CONFIG_TYPE_PASSIVE_SKILL = 116 UMETA(DisplayName = "CSV_CONFIG_TYPE_PASSIVE_SKILL"),
	///音效配置表
	CSV_CONFIG_TYPE_AUDIO = 119 UMETA(DisplayName = "CSV_CONFIG_TYPE_AUDIO"),
	///人物状态配置表
	CSV_CONFIG_TYPE_STATE = 121 UMETA(DisplayName = "CSV_CONFIG_TYPE_STATE"),
	///攻城梯配置表
	CSV_CONFIG_ATTACK_CITY_LADDER = 122 UMETA(DisplayName = "CSV_CONFIG_ATTACK_CITY_LADDER"),
	///场景音乐配置表
	CSV_CONFIG_TYPE_SCENE_MUSIC = 125 UMETA(DisplayName = "CSV_CONFIG_TYPE_SCENE_MUSIC"),
	///语音配置表
	CSV_CONFIG_TYPE_VOICE = 127 UMETA(DisplayName = "CSV_CONFIG_TYPE_VOICE"),
	///关卡映射配置表
	CSV_CONFIG_TYPE_LEVELMAP = 129 UMETA(DisplayName = "CSV_CONFIG_TYPE_LEVELMAP"),
	///区域数据配置表
	CSV_CONFIG_TYPE_AREA_DATA = 133 UMETA(DisplayName = "CSV_CONFIG_TYPE_AREA_DATA"),
	///飞行路线配置表
	CSV_CONFIG_TYPE_FLY_PATROL = 135 UMETA(DisplayName = "CSV_CONFIG_TYPE_FLY_PATROL"),
	///位面触发配置表
	CSV_CONFIG_TYPE_PLANE_TRIGGER = 137 UMETA(DisplayName = "CSV_CONFIG_TYPE_PLANE_TRIGGER"),
	///Buff数据配置表
	CSV_CONFIG_TYPE_BUFF = 139 UMETA(DisplayName = "CSV_CONFIG_TYPE_BUFF"),
	///Buff效果纹理配置表
	CSV_CONFIG_TYPE_BUFF_CLIENT_EFFECT = 140 UMETA(DisplayName = "CSV_CONFIG_TYPE_BUFF_CLIENT_EFFECT"),
	///Boss战斗区域配置表
	CSV_CONFIG_TYPE_BOSS_AREA = 141 UMETA(DisplayName = "CSV_CONFIG_TYPE_BOSS_AREA"),
	///物品配置表
	CSV_CONFIG_ITEMDATA = 143 UMETA(DisplayName = "CSV_CONFIG_ITEMDATA"),
	///物品Icon路径配置表
	CSV_CONFIG_ITEM_ICON = 144 UMETA(DisplayName = "CSV_CONFIG_ITEM_ICON"),
	///物品类型文字
	CSV_CONFIG_ITEMTYPEINFO = 145 UMETA(DisplayName = "CSV_CONFIG_ITEMTYPEINFO"),
	///客户端中文配置表
	CSV_CONFIG_CHINESE = 146 UMETA(DisplayName = "CSV_CONFIG_CHINESE"),
	///字符串与蓝图类配置表
	CSV_CONFIG_STRTOCLASS = 147 UMETA(DisplayName = "CSV_CONFIG_STRTOCLASS"),
	/// 输入配置表
	CSV_CONFIG_INPUT = 149 UMETA(DisplayName = "CSV_CONFIG_TYPE_INPUT"),
	/// 快捷键配置表
	CSV_CONFIG_SHORTCUT_KEY = 150 UMETA(DisplayName = "CSV_CONFIG_TYPE_SHORTCUT_KEY"),
	/// 动作中断配置表
	CSV_CONFIG_ACTION_BREAK = 151 UMETA(DisplayName = "CSV_CONFIG_TYPE_ACTION_BREAK"),
	/// 势力关系配置表
	CSV_CONFIG_FACTION_RELATION = 155 UMETA(DisplayName = "CSV_CONFIG_FACTION_RELATION"),
	///任务相关entity可见性配置表
	CSV_CONFIG_QUEST_ENTITY_VISIBLE = 162 UMETA(DisplayName = "CSV_CONFIG_QUEST_ENTITY_VISIBLE"),
	///怪物配置表
	CSV_CONFIG_MONSTER = 163 UMETA(DisplayName = "CSV_CONFIG_MONSTER"),
	///NPC配置表
	CSV_CONFIG_NPC = 164 UMETA(DisplayName = "CSV_CONFIG_NPC"),
	///默认快捷键配置表
	CSV_CONFIG_DEFAULT_SHORTCUTKEY = 165 UMETA(DisplayName = "CSV_CONFIG_DEFAULT_SHORTCUTKEY"),
	///默认自定义配置表
	CSV_CONFIG_DEFAULT_COSTOM = 166 UMETA(DisplayName = "CSV_CONFIG_DEFAULT_COSTOM"),
	///选择和创建界面的动画
	CSV_CONFIG_SELECT_CREAT_ACTION = 167 UMETA(DisplayName = "CSV_CONFIG_SELECT_CREAT_ACTION"),
	///SpawnTransform配置表
	CSV_CONFIG_SPAWN_TRANSFORM = 169 UMETA(DisplayName = "CSV_CONFIG_SPAWN_TRANSFORM"),
	///SpaceEntityRelationCfg配置表
	CSV_CONFIG_SPACE_ENTITY_RELATION = 170 UMETA(DisplayName = "CSV_CONFIG_SPACE_ENTITY_RELATION"),
	///CameraParamsEvent配置表
	CSV_CONFIG_CAMERA_PARAMS_EVENT = 171 UMETA(DisplayName = "CSV_CONFIG_CAMERA_PARAMS_EVENT"),
	///玩家各方向速度
	CSV_CONFIG_DIR_MOVE_SPEED = 172 UMETA(DisplayName = "CSV_CONFIG_DIR_MOVE_SPEED"),
	///系统默认表情
	CSV_CONFIG_DEFAULT_EMOTES = 173 UMETA(DisplayName = "CSV_CONFIG_DEFAULT_EMOTES"),
	///自定义文字表情表情
	CSV_CONFIG_CUSTOM_TEXT_EMOTES = 174 UMETA(DisplayName = "CSV_CONFIG_CUSTOM_TEXT_EMOTES"),
	///练兵任务配置表
	CSV_CONFIG_LBC_TASK = 175 UMETA(DisplayName = "CSV_CONFIG_LBC_TASK"),
	///Pet配置表
	CSV_CONFIG_PET = 176 UMETA(DisplayName = "CSV_CONFIG_PET"),
	///光墙数据配置
	CSV_CONFIG_LIGHT_WALL_DATA = 177 UMETA(DisplayName = "CSV_CONFIG_LIGHT_WALL_DATA"),
	///SpaceDynamicEffect配置表
	CSV_CONFIG_SPACE_DYNAMIC_EFFECT = 179 UMETA(DisplayName = "CSV_CONFIG_SPACE_DYNAMIC_EFFECT"),
	///骑士模型动作配置表
	CSV_CONFIG_RIDE_ANIM_DATA = 180 UMETA(DisplayName = "CSV_CONFIG_RIDE_ANIM_DATA"),
	///NPC位置数据配置表，用于自动寻路根据SpaceName和NPC的ID找到对应的位置
	CSV_CONFIG_NPC_POINT_DATAS = 181 UMETA(DisplayName = "CSV_CONFIG_NPC_POINT_DATAS"),
	///entity Buff可见性配置表
	CSV_CONFIG_BUFF_ENTITY_VISIBLE = 182 UMETA(DisplayName = "CSV_CONFIG_BUFF_ENTITY_VISIBLE"),
	///鼠标图表配置表
	CSV_CURSOR_DATAS = 184 UMETA(DisplayName = "CSV_CURSOR_DATAS"),
	///背包格子解锁消耗配置
	CSV_CONFIG_KITBAG_GRID_COST = 186 UMETA(DisplayName = "CSV_CONFIG_KITBAG_GRID_COST"),
	///装备强化和锁星配置表
	CSV_EUQIPLV_DATAS = 187 UMETA(DisplayName = "CSV_EUQIPLV_DATAS"),
	///装备强化消耗配置表
	CSV_EQUIP_INTENSIFY_COST = 188 UMETA(DisplayName = "CSV_EQUIP_INTENSIFY_COST"),
	///装备回火消耗配置表
	CSV_EQUIP_BACKFIRE_COST = 189 UMETA(DisplayName = "CSV_EQUIP_BACKFIRE_COST"),
	///装备回火消耗配置表
	CSV_EQUIP_RESTORE_COST = 190 UMETA(DisplayName = "CSV_EQUIP_RESTORE_COST"),
	///颜色alias配置表
	CSV_CONFIG_COLOR_ALIAS = 191 UMETA(DisplayName = "CSV_CONFIG_COLOR_ALIAS"),
	///脚印配置表
	CSV_CONFIG_FOOT_PRINT_DATA = 192 UMETA(DisplayName = "CSV_CONFIG_FOOT_PRINT_DATA"),
	///模型绑定表
	CSV_CONFIG_HOLD_PET_MESH_DATA = 193 UMETA(DisplayName = "CSV_CONFIG_HOLD_PET_MESH_DATA"),
	///自动寻路路线配置表
	CSV_CONFIG_AUTO_NAVIGATE_PATH_DATA = 194 UMETA(DisplayName = "CSV_CONFIG_AUTO_NAVIGATE_PATH_DATA"),
	///碰撞配置表
	CSV_CONFIG_COLLIDE_DATA = 195 UMETA(DisplayName = "CSV_CONFIG_COLLIDE_DATA"),
	///载具配置表
	CSV_CONFIG_CARRIER = 196 UMETA(DisplayName = "CSV_CONFIG_CARRIER"),
	///大地图NPC配置表
	CSV_CONFIG_NPC_BIGMAP_DATA = 197 UMETA(DisplayName = "CSV_CONFIG_NPC_BIGMAP_DATA"),
	///剧情事件配置表
	CSV_CONFIG_STORY_EVENT = 198 UMETA(DisplayName = "CSV_CONFIG_STORY_EVENT"),
	///自动战斗默认设置配置表
	CSV_CONFIG_AUTOFIGHT_SETTING_DEFAULT = 199 UMETA(DisplayName = "CSV_CONFIG_AUTOFIGHT_SETTING_DEFAULT"),
	///剧情事件配置表
	CSV_CONFIG_STORY_ANIM_EVENT = 200 UMETA(DisplayName = "CSV_CONFIG_STORY_ANIM_EVENT"),
	CSV_CONFIG_TRIGGER_TIPS = 201 UMETA(DisplayName = "CSV_CONFIG_TRIGGER_TIPS"),
	///选择职业提示POS
	CSV_CONFIG_PROFESSION_DATA = 202 UMETA(DisplayName = "CSV_CONFIG_PROFESSION_DATA"),
	///传送点配置表
	CSV_CONFIG_TELEPORT_POINT_DATA = 203 UMETA(DisplayName = "CSV_CONFIG_TELEPORT_POINT_DATA"),
	///跨地图寻路配置表
	CSV_CONFIG_CROSS_MAP_NAVIGATE_DATA = 204 UMETA(DisplayName = "CSV_CONFIG_CROSS_MAP_NAVIGATE_DATA"),
	///技能测试配置表
	CSV_CONFIG_TYPE_SKILL_TEST = 205 UMETA(DisplayName = "CSV_CONFIG_TYPE_SKILL_TEST"),
	///状态对应光效表
	CSV_CONFIG_EFFECTSTATE_EFFECT = 206 UMETA(DisplayName = "CSV_CONFIG_EFFECTSTATE_EFFECT"),
	///操作类表
	CSV_CONFIG_OPERATION_CLASS = 207 UMETA(DisplayName = "CSV_CONFIG_OPERATION_CLASS"),
	///默认控制模式
	CSV_CONFIG_DEFAULT_CONTROL_MODE = 208 UMETA(DisplayName = "CSV_CONFIG_DEFAULT_CONTROL_MODE"),
	///默认操作模式
	CSV_CONFIG_DEFAULT_OPERATION_MODE = 209 UMETA(DisplayName = "CSV_CONFIG_DEFAULT_OPERATION_MODE"),
	///控制模式
	CSV_CONFIG_CONTROL_MODE = 210 UMETA(DisplayName = "CSV_CONFIG_CONTROL_MODE"),
	///操作模式
	CSV_CONFIG_OPERATION_MODE = 211 UMETA(DisplayName = "CSV_CONFIG_OPERATION_MODE"),
	///屏蔽字配置表格
	CSV_CONFIG_TEXT_SHIELD_DATA = 212 UMETA(DisplayName = "CSV_CONFIG_TEXT_SHIELD_DATA"),
	///屏蔽字配置表格
	CSV_CONFIG_TEXT_SHIELD_TEST_DATA = 213 UMETA(DisplayName = "CSV_CONFIG_TEXT_SHIELD_TEST_DATA"),
	///帮会技能
	CSV_CONFIG_TONG_SKILL_DATA = 214 UMETA(DisplayName = "CSV_CONFIG_TONG_SKILL_DATA"),
	///帮会权限
	CSV_CONFIG_TONG_GRADE_DATA = 216 UMETA(DisplayName = "CSV_CONFIG_TONG_GRADE_DATA"),
	///帮会建筑等级
	CSV_CONFIG_TONG_BUILD_LEVEL_DATA = 218 UMETA(DisplayName = "CSV_CONFIG_TONG_BUILD_LEVEL_DATA"),
	///NPC商店
	CSV_CONFIG_NPC_SHOP_DATA = 220 UMETA(DisplayName = "CSV_CONFIG_NPC_SHOP_DATA"),
	///帮会仓库事件信息
	CSV_CONFIG_TONG_STORE_EVENT_DATA = 221 UMETA(DisplayName = "CSV_CONFIG_TONG_STORE_EVENT_DATA"),
	///帮会事件记录
	CSV_CONFIG_TONG_EVENT_DATA = 222 UMETA(DisplayName = "CSV_CONFIG_TONG_EVENT_DATA"),
	///商店类型
	CSV_CONFIG_SHOP_TYPE_DATA = 223 UMETA(DisplayName = "CSV_CONFIG_SHOP_TYPE_DATA"),
	///原地复活消耗表
	CSV_CONFIG_REVIVE_COST_DATA = 224 UMETA(DisplayName = "CSV_CONFIG_REVIVE_COST_DATA"),
	///装备洗练消耗
	CSV_CONFIG_SHUFFLE_TYPE_DATA = 227 UMETA(DisplayName = "CSV_CONFIG_SHUFFLE_TYPE_DATA"),
	///装备重铸消耗
	CSV_CONFIG_RECAST_COST_DATA = 228 UMETA(DisplayName = "CSV_CONFIG_RECAST_COST_DATA"),
	///装备传星消耗
	CSV_CONFIG_BIOGRAPHY_COST_DATA = 229 UMETA(DisplayName = "CSV_CONFIG_BIOGRAPHY_COST_DATA"),
	///法宝配置表
	CSV_CONFIG_FABAO_DATA = 230 UMETA(DisplayName = "CSV_CONFIG_FABAO_DATA"),
	///装备附加属性配置表
	CSV_CONFIG_EQUIP_PROPERTY_DATA = 231 UMETA(DisplayName = "CSV_CONFIG_EQUIP_PROPERTY_DATA"),
	///装备打造配置表
	CSV_CONFIG_EQUIP_COMPOSE_DATA = 232 UMETA(DisplayName = "CSV_CONFIG_EQUIP_COMPOSE_DATA"),
	///战魂商店
	CSV_CONFIG_COMBAT_SOUL_SHOP_DATA = 234 UMETA(DisplayName = "CSV_CONFIG_COMBAT_SOUL_SHOP_DATA"),
	///魂卫商店
	CSV_CONFIG_GUARD_SOUL_SHOP_DATA = 235 UMETA(DisplayName = "CSV_CONFIG_GUARD_SOUL_SHOP_DATA"),
	///魂塔商店
	CSV_CONFIG_PAGODA_SOUL_SHOP_DATA = 236 UMETA(DisplayName = "CSV_CONFIG_PAGODA_SOUL_SHOP_DATA"),
	///位面阻挡光墙
	CSV_CONFIG_FAREA_TERRAINCLASSIFICATION_DATA = 237 UMETA(DisplayName = "CSV_CONFIG_FAREA_TERRAINCLASSIFICATION_DATA"),
	///技能树数据配置
	CSV_CONFIG_SKILLTREE_DATA = 238 UMETA(DisplayName = "CSV_CONFIG_SKILLTREE_DATA"),
	///技能指导老师数据配置
	CSV_CONFIG_SKILLTEACHER_DATA = 239 UMETA(DisplayName = "CSV_CONFIG_SKILLTEACHER_DATA"),
	///技能学习数据配置
	CSV_CONFIG_SKILLLEARN_DATA = 240 UMETA(DisplayName = "CSV_CONFIG_SKILLLEARN_DATA"),
	///飞行绑定Actor
	CSV_CONFIG_FLY_BIND_MESH_DATA = 241 UMETA(DisplayName = "CSV_CONFIG_FLY_BIND_MESH_DATA"),
	///摆摊点
	CSV_CONFIG_STALL_DATA = 242 UMETA(DisplayName = "CSV_CONFIG_STALL_DATA"),
	///签到奖励
	CSV_CONFIG_SIGN_IN_REWARD_DATA = 244 UMETA(DisplayName = "CSV_CONFIG_SIGN_IN_REWARD_DATA"),
	///累计签到奖励
	CSV_CONFIG_TOTAL_SIGN_REWARD_DATA = 245 UMETA(DisplayName = "CSV_CONFIG_TOTAL_SIGN_REWARD_DATA"),
	///累计签到奖励
	CSV_CONFIG_QTE_DATA = 246 UMETA(DisplayName = "CSV_CONFIG_QTE_DATA"),
	///累计签到奖励
	CSV_SYSTEM_DEFAULT_DATA = 247 UMETA(DisplayName = "CSV_SYSTEM_DEFAULT_DATA"),
	///媒体配置表
	CSV_MEDIA_PLAYER_DATA = 248 UMETA(DisplayName = "CSV_MEDIA_PLAYER_DATA"),
	///动态半身像配置表
	CSV_CONFIG_DYNAMIC_HEAD_DATA = 249 UMETA(DisplayName = "CSV_CONFIG_DYNAMIC_HEAD_DATA"),
	///幻兽头像配置表
	CSV_CONFIG_PET_HEAD_ICON_DATA = 250 UMETA(DisplayName = "CSV_CONFIG_PET_HEAD_ICON_DATA"),
	///小地图配置表
	CSV_CONFIG_MINIMAP_DATA = 251 UMETA(DisplayName = "CSV_CONFIG_MINIMAP_DATA"),
	///英雄王座Entity标记图标配置表
	CSV_CONFIG_YXWZ_SIGN_ICON_DATA = 252 UMETA(DisplayName = "CSV_CONFIG_YXWZ_SIGN_ICON_DATA"),
	///粒子预加载配置
	CSV_CONFIG_EFFECT_PRELOAD_DATA = 253 UMETA(DisplayName = "CSV_CONFIG_EFFECT_PRELOAD_DATA"),
	///英雄王座 中立商店
	CSV_CONFIG_NEURAL_GUARD_SHOP_DATA = 254 UMETA(DisplayName = "CSV_CONFIG_NEURAL_GUARD_SHOP_DATA"),
	///捏脸数据表
	CSV_CONFIG_MODIFY_FACE__DATA = 255 UMETA(DisplayName = "CSV_CONFIG_MODIFY_FACE__DATA"),
	///捏脸限制拉伸伸缩长度表
	CSV_CONFIG_BONE_FACE_LIMIT_DATA = 100 UMETA(DisplayName = "CSV_CONFIG_BONE_FACE_LIMIT_DATA"),
	///装备名字表
	CSV_CONFIG_EQUIP_NAME_DATA = 99 UMETA(DisplayName = "CSV_CONFIG_EQUIP_NAME_DATA"),
	///tips表
	CSV_CONFIG_HOVER_TIPS_DATA = 98 UMETA(DisplayName = "CSV_CONFIG_HOVER_TIPS_DATA"),
	///物品品质表
	CSV_CONFIG_ITEM_QUALITY_DATA = 97 UMETA(DisplayName = "CSV_CONFIG_ITEM_QUALITY_DATA"),
	///阵营图标配置
	CSV_CONFIG_ROLE_PROFESSION_DATA = 96 UMETA(DisplayName = "CSV_CONFIG_PROFESSION_DATA"),
	///后台预加载UI图标配置
	CSV_CONFIG_ASYNCLOAD_UI_TEXTURE_DATA = 95 UMETA(DisplayName = "CSV_CONFIG_ASYNCLOAD_UI_TEXTURE_DATA"),
	///系统开启配置
	CSV_CONFIG_SYATEM_OPEN_DATA = 94 UMETA(DisplayName = "CSV_CONFIG_SYATEM_OPEN_DATA"),
	///tips配置
	CSV_CONFIG_TIPS_DATA = 93 UMETA(DisplayName = "CSV_CONFIG_TIPS_DATA"),
	///功能按钮配置
	CSV_CONFIG_FUNCTION_BTN_DATA = 92 UMETA(DisplayName = "CSV_CONFIG_FUNCTION_BTN_DATA"),
	///聊天频道配置
	CSV_CONFIG_CHAT_CHANNEL_DATA = 91 UMETA(DisplayName = "CSV_CONFIG_CHAT_CHANNEL_DATA"),
	///飞剑载具配置表
	CSV_CONFIG_FLY_CARRIER = 90 UMETA(DisplayName = "CSV_CONFIG_FLY_CARRIER"),
	///商城推荐商品配置
	CSV_CONFIG_MALL_RECOMMENT_DATA = 89 UMETA(DisplayName = "CSV_CONFIG_MALL_RECOMMENT_DATA"),
	///城搜索商品配置
	CSV_CONFIG_MALL_GOODS_DATA = 88 UMETA(DisplayName = "CSV_CONFIG_MALL_GOODS_DATA"),
	///任务数据配置
	CSV_CONFIG_QUEST_DATA = 86 UMETA(DisplayName = "CSV_CONFIG_QUEST_DATA"),
	///玩家当前光照配置
	CSV_CONFIG_PLAYER_LIGHT_DATA = 87 UMETA(DisplayName = "CSV_CONFIG_PLAYER_LIGHT_DATA"),
	///被动技能栏配置
	CSV_CONFIG_PASSIVESKILLBAR_DATA = 85 UMETA(DisplayName = "CSV_CONFIG_PASSIVESKILLBAR_DATA"),
	///镜头模型加载配置
	CSV_CONFIG_STROY_LOAD_MODEL_DATA = 84 UMETA(DisplayName = "CSV_CONFIG_STROY_LOAD_MODEL_DATA"),
	///被动技能树数据配置
	CSV_CONFIG_PASSIVE_SKILL_TREE_DATA = 83 UMETA(DisplayName = "CSV_CONFIG_PASSIVE_SKILL_TREE_DATA"),
	///帮会神兽召唤3D模型配置
	CSV_CONFIG_TONG_NAGUAL_MODEL_DATA = 82 UMETA(DisplayName = "CSV_CONFIG_TONG_NAGUAL_MODEL_DATA"),
	///新活动日程配置表
	CSV_NEW_CONFIG_CROND = 81 UMETA(DisplayName = "CSV_NEW_CONFIG_CROND"),
	///半身像模型偏移位置配置表
	CSV_CONFIG_DYNAMIC_HEAD_TRAN_DATA = 80 UMETA(DisplayName = "CSV_CONFIG_DYNAMIC_HEAD_TRAN_DATA"),
	///客户端AI数据
	CSV_CONFIG_MONSTER_BTREE = 79 UMETA(DisplayName = "CSV_CONFIG_MONSTER_BTREE"),
	///活动周历字段配置表
	CSV_CONFIG_WEEK_CROND_DATA = 78 UMETA(DisplayName = "CSV_CONFIG_WEEK_CROND_DATA"),
	///兵营配置表
	CSV_CONFIG_BARRACKS_DATA = 77 UMETA(DisplayName = "CSV_CONFIG_BARRACKS_DATA"),
	///兵的技能升级数据
	CSV_CONFIG_BARRACKS_SKILL_DATA = 76 UMETA(DisplayName = "CSV_CONFIG_BARRACKS_SKILL_DATA"),
	///轮回秘境工具打造消耗数据表
	CSV_CONFIG_TOOL_COST_DATA = 75 UMETA(DisplayName = "CSV_CONFIG_TOOL_COST_DATA"),
	///轮回秘境绿装打造消耗数据表
	CSV_CONFIG_GEQUIP_COST_DATA = 74 UMETA(DisplayName = "CSV_CONFIG_GEQUIP_COST_DATA"),
	///轮回秘境乾坤鼎打造消耗数据表
	CSV_CONFIG_TRIPOD_COST_DATA = 73 UMETA(DisplayName = "CSV_CONFIG_TRIPOD_COST_DATA"),
	///轮回秘境 装备熔炼数据表
	CSV_CONFIG_MELTHING_EQUIP_DATA = 72 UMETA(DisplayName = "CSV_CONFIG_MELTHING_EQUIP_DATA"),
	///轮回秘境 工坊、乾坤鼎的物品分类
	CSV_CONFIG_WORKSHOP_CATEGORY_DATA = 71 UMETA(DisplayName = "CSV_CONFIG_WORKSHOP_CATEGORY_DATA"),
	///轮回秘境 套装属性和前缀名称
	CSV_CONFIG_WORKSHOP_SUITNAME_DATA = 70 UMETA(DisplayName = "CSV_CONFIG_WORKSHOP_SUITNAME_DATA"),
	///文字动画消息
	CSV_CONFIG_TEXT_ANIMATION_MESSAGE_DATA = 69 UMETA(DisplayName = "CSV_CONFIG_TEXT_ANIMATION_MESSAGE_DATA"),
	///轮回秘境商店刷新消耗
	CSV_CONFIG_LHMJ_SKOP_REFLASH_COST_DATA = 68 UMETA(DisplayName = "CSV_CONFIG_LHMJ_SKOP_REFLASH_COST_DATA"),
	//玩家经验
	CSV_CONFIG_ROLE_EXP = 256 UMETA(DisplayName = "CSV_CONFIG_ROLE_EXP"),
	//建筑消耗数据
	CSV_CONFIG_BULID_DEPLETE_DATA = 67 UMETA(DisplayName = "CSV_CONFIG_BULID_DEPLETE_DATA"),
	//灵泉产出数据
	CSV_CONFIG_LINGQUAN_PRODUCE_DATA = 66 UMETA(DisplayName = "CSV_CONFIG_LINGQUAN_PRODUCE_DATA"),
	///战场小兵不同关系下的外貌
	CSV_CONFIG_MODIFY_BATTLEFIELD_APPEARANCE = 257 UMETA(DisplayName = "CSV_CONFIG_MODIFY_BATTLEFIELD_APPEARANCE"),
	///幻兽模型偏移配置表
	CSV_CONFIG_PET_MODEL_TRANSFORM = 65 UMETA(DisplayName = "CSV_CONFIG_PET_MODEL_TRANSFORM"),
	///灵田种植数据
	CSV_CONFIG_LING_TIAN_PLANT_DATA = 64 UMETA(DisplayName = "CSV_CONFIG_LING_TIAN_PLANT_DATA"),
	///粒子测试配置表
	CSV_CONFIG_TYPE_PARTICLE_TEST = 63 UMETA(DisplayName = "CSV_CONFIG_TYPE_PARTICLE_TEST"),
	///Buff数据配置表
	CSV_CONFIG_TYPE_BUFF_TEST = 62 UMETA(DisplayName = "CSV_CONFIG_TYPE_BUFF_TEST"),
	///轮回秘境倍率消耗数据表
	CSV_CONFIG_LHMJ_COMPOSE_RATE_COST_DATA = 61 UMETA(DisplayName = "CSV_CONFIG_LHMJ_COMPOSE_RATE_COST_DATA"),
	///随机限量商品配置表
	CSV_CONFIG_NPC_RANDOM_LIMIT_SHOP_DATA = 258 UMETA(DisplayName = "CSV_CONFIG_NPC_RANDOM_LIMIT_SHOP_DATA"),
	///天兵营复活将领费用表
	CSV_CONFIG_BARRACKS_REVIVE_COST_DATA = 259 UMETA(DisplayName = "CSV_CONFIG_BARRACKS_REVIVE_COST_DATA"),
	///练兵场区域数据表
	CSV_CONFIG_TRAIN_GROUND_AREA_DATA = 260 UMETA(DisplayName = "CSV_CONFIG_TRAIN_GROUND_AREA_DATA"),
	///快捷栏数据表
	CSV_CONFIG_QUICK_SKILL_DATA = 261 UMETA(DisplayName = "CSV_CONFIG_QUICK_SKILL_DATA"),
	///仓库格子解锁消耗配置
	CSV_CONFIG_STORE_GRID_COST = 262 UMETA(DisplayName = "CSV_CONFIG_STORE_GRID_COST"),
	///被动技能学习数据配置
	CSV_CONFIG_PASSIVESKILL_LEARN_DATA = 263 UMETA(DisplayName = "CSV_CONFIG_PASSIVESKILL_LEARN_DATA"),
	///神通技能数据配置
	CSV_CONFIG_SHENTONGSKILLTREE_DATA = 264 UMETA(DisplayName = "CSV_CONFIG_SHENTONGSKILLTREE_DATA"),
	///帮会争霸 区域数据表
	CSV_CONFIG_BHZB_POINT_DATA = 265 UMETA(DisplayName = "CSV_CONFIG_BHZB_POINT_DATA"),
	///神秘商人商品配置表
	CSV_CONFIG_MYSTERIOUS_SHOP_DATA = 266 UMETA(DisplayName = "CSV_CONFIG_MYSTERIOUS_SHOP_DATA"),
	///基准伤害值表
	CSV_CONFIG_COMBAT_DAMAGER_DATA = 267 UMETA(DisplayName = "CSV_CONFIG_COMBAT_DAMAGER_DATA"),
	///练兵场配置表
	CSV_CONFIG_LBC_DATA = 268 UMETA(DisplayName = "CSV_CONFIG_LBC_DATA"),
	///商城商品配置
	CSV_CONFIG_STORE_GOODS_DATA = 269 UMETA(DisplayName = "CSV_CONFIG_STORE_GOODS_DATA"),
	///商城外观商品配置
	CSV_CONFIG_STORE_APPEARANCE_DATA = 270 UMETA(DisplayName = "CSV_CONFIG_STORE_APPEARANCE_DATA"),
	///帮会商店帮会掠夺战分页配置
	CSV_CONFIG_TONG_PLUNDER_SHOP_DATA = 271 UMETA(DisplayName = "CSV_CONFIG_TONG_PLUNDER_SHOP_DATA"),
	///传承技能树数据配置
	CSV_CONFIG_CHUANCHENG_SKILL_TREE_DATA = 272 UMETA(DisplayName = "CSV_CONFIG_CHUANCHENG_SKILL_TREE_DATA"),
	///帮会升级数据配置
	CSV_CONFIG_TONG_LEVEL_DATA = 273 UMETA(DisplayName = "CSV_CONFIG_TONG_LEVEL_DATA"),
	/// 幻兽神通AI配置
	CSV_CONFIG_PET_ST_AI_DATA = 274 UMETA(DisplayName = "CSV_CONFIG_PET_ST_AI_DATA"),
	///传承技能学习数据配置
	CSV_CONFIG_CHUANCHENG_SKILL_LEARN_DATA = 275 UMETA(DisplayName = "CSV_CONFIG_CHUANCHENG_SKILL_LEARN_DATA"),
	///幻兽神通技能数据配置
	CSV_CONFIG_PET_SHENTONG_SKILL_TREE_DATA = 276 UMETA(DisplayName = "CSV_CONFIG_PET_SHENTONG_SKILL_TREE_DATA"),
	///掉落每轮竞拍的相关参数配置
	CSV_CONFIG_AUCTION_DATA = 277 UMETA(DisplayName = "CSV_CONFIG_AUCTION_DATA"),
	///Buff开关条件显示配置
	CSV_CONFIG_BUFF_TARGETACTFORBID_DATA = 278 UMETA(DisplayName = "CSV_CONFIG_BUFF_TARGETACTFORBID_DATA"),
	///幻兽技能学习数据配置
	CSV_CONFIG_PET_SKILL_LEARN_DATA = 279 UMETA(DisplayName = "CSV_CONFIG_PET_SKILL_LEARN_DATA"),
};



///资源加载的优先级别
UENUM()
enum ASSET_LOAD_PRIORITY
{
	LOAD_PRIORITY_1 = 1,
	LOAD_PRIORITY_2 = 2,
	LOAD_PRIORITY_3 = 3,
	LOAD_PRIORITY_4 = 4,
	LOAD_PRIORITY_5 = 5,
};