#pragma once
#include "CoreMinimal.h"

/**
* 文件名称：SpaceEventType.h
* 功能说明：
* 文件作者：chenweilan
* 目前维护：hejingke
* 创建时间：2016-10-25
*/

enum SPACE_EVENT_TYPE
{
	SPACE_EVENT_TYPE_SPACE_ON_INIT = 1,
	SPACE_EVENT_TYPE_SPACE_ON_TIMER = 2,
	SPACE_EVENT_TYPE_ROLE_ENTER_SPACE = 3,
	SPACE_EVENT_TYPE_ROLE_CHANGE_AREA = 4,
	SPACE_EVENT_TYPE_MONSTER_DIE = 5,
	SPACE_EVENT_TYPE_MONSTER_CREATE = 6,
	SPACE_EVENT_TYPE_MONSTER_CHANGE_HP = 7,
	SPACE_EVENT_TYPE_SPACE_STAGE_COMPLETE = 8,
	SPACE_EVENT_TYPE_SPACE_ON_SUCCESS = 9,
	SPACE_EVENT_TYPE_SPACE_ON_FAILURE = 10,
	SPACE_EVENT_TYPE_SPACE_STAGE_START = 11,
	SPACE_EVENT_TYPE_MONSTER_DESTROY = 12,
	SPACE_EVENT_TYPE_ROLE_LOGIN_DIFF_SPACE = 13,
	SPACE_EVENT_TYPE_SPACE_CON_CHANGE = 14,
	SPACE_EVENT_TYPE_ROLE_ENTER_AREA = 15,
	SPACE_EVENT_TYPE_SPACE_COUNT_CHANGE = 16,
	SPACE_EVENT_TYPE_ROLE_LEAVE_SPACE = 17,
	SPACE_EVENT_TYPE_ROLE_ADD_ITEM	= 18,
	SPACE_EVENT_TYPE_ROLE_DIE = 19,
	SPACE_EVENT_TYPE_SPACE_STATISTICS_COMPLETE = 20,
	SPACE_EVENT_TYPE_ROLE_ENTER_SPACE_COM = 21,
	SPACE_EVENT_TYPE_SPAWN_POINT_LOAD_OVER = 22,
	SPACE_EVENT_TYPE_ON_ROLE_BEKILL = 23,
	SPACE_EVENT_TYPE_ON_STATE_CHANGE = 24,
	SPACE_EVENT_TYPE_ON_MONSTER_BEKILL = 25,
	SPACE_EVENT_TYPE_ROLE_REMOVE_ITEM = 26,
	SPACE_EVENT_TYPE_ROLE_LEAVE_AREA = 27,
};