"""
自由状态	 =1
战斗状态 =2
死亡状态 =3
未决状态 =4


----------NPC职业------------
宠物商 = 0
武器商 = 1
药品商 = 2
...
"""
#---------------------副本事件触发类型--------------------
SPACE_EVENT_TRIGGER_TYPE_MONSTER	= 1
SPACE_EVENT_TRIGGER_TYPE_ROLE		= 2
SPACE_EVENT_TRIGGER_TYPE_SPACE		= 3

#---------------------副本事件类型------------------------
SPACE_EVENT_TYPE_SPACE_ON_INIT		= 1		#副本初始化
SPACE_EVENT_TYPE_SPACE_ON_TIMER		= 2		#副本timer到达
SPACE_EVENT_TYPE_ROLE_ENTER_SPACE	= 3		#玩家进副本
SPACE_EVENT_TYPE_ROLE_CHANGE_AREA	= 4		#玩家世界区域改变
SPACE_EVENT_TYPE_MONSTER_DIE		= 5		#怪物死亡
SPACE_EVENT_TYPE_MONSTER_CREATE		= 6		#怪物或NPC创建
SPACE_EVENT_TYPE_MONSTER_CHANGE_HP	= 7		#怪物血量改变
SPACE_EVENT_TYPE_SPACE_STAGE_COMPLETE	= 8	#副本某阶段完成
SPACE_EVENT_TYPE_SPACE_ON_SUCCESS	= 9		#副本通关
SPACE_EVENT_TYPE_SPACE_ON_FAILURE	= 10	#副本失败
SPACE_EVENT_TYPE_SPACE_STAGE_START	= 11	#副本某阶段开始
SPACE_EVENT_TYPE_MONSTER_DESTROY 	= 12	#怪物或NPC销毁
SPACE_EVENT_TYPE_ROLE_LOGIN_DIFF_SPACE = 13	#玩家登陆其他地图
SPACE_EVENT_TYPE_SPACE_CON_CHANGE	= 14	#副本条件改变
SPACE_EVENT_TYPE_ROLE_ENTER_AREA	= 15	#玩家进入某范围
SPACE_EVENT_TYPE_SPACE_COUNT_CHANGE	= 16	#副本计数改变
SPACE_EVENT_TYPE_ROLE_LEAVE_SPACE	= 17	#玩家离开副本
SPACE_EVENT_TYPE_ROLE_ADD_ITEM		= 18	#玩家获得物品
SPACE_EVENT_TYPE_ROLE_DIE			= 19	#玩家死亡时
SPACE_EVENT_TYPE_SPACE_STATISTICS_COMPLETE= 20	#副本某统计完成
SPACE_EVENT_TYPE_ROLE_ENTER_SPACE_COM= 21	#玩家进入副本且场景加载完毕
SPACE_EVENT_TYPE_SPAWN_POINT_LOAD_OVER= 22	#刷新点加载完毕
SPACE_EVENT_TYPE_ON_ROLE_BEKILL		= 23	#玩家被击杀的事件
SPACE_EVENT_TYPE_ON_STATE_CHANGE	= 24	#玩家状态改变事件
SPACE_EVENT_TYPE_ON_MONSTER_BEKILL	= 25	#怪物被击杀的事件
SPACE_EVENT_TYPE_ROLE_REMOVE_ITEM	= 26	#玩家移除物品
SPACE_EVENT_TYPE_ROLE_LEAVE_AREA 	= 27	#玩家离开某范围
SPACE_EVENT_TYPE_SPACE_STAGE_TASK_COMPLETE = 28	#副本某阶段目标完成
SPACE_EVENT_TYPE_ROLE_CHANGE_HP		= 29	#玩家血量改变
SPACE_EVENT_STOP_PLAY_SOUND 	    = 30 	#语音停止播放事件
SPACE_EVENT_TYPE_PARACHUTING_OVER 	    = 31 #玩家跳伞结束事件

#-----------------玩家离开副本原因-----------------------
LEAVE_SPACE_REASON_TELEPORT	= 1
LEAVE_SPACE_REASON_LOGOUT	= 2

#-----------------副本阶段任务类型-----------------------
SPACE_STAGE_TASK_NONE			= 0
SPACE_STAGE_TASK_KILL_MONSTER	= 1
SPACE_STAGE_TASK_TRIGGER_BOX	= 2
SPACE_STAGE_TASK_CONDITION_CHANGE = 3
SPACE_STAGE_TASK_GET_ITEM		= 4
SPACE_STAGE_TASK_ENTER_AREA		= 5
SPACE_STAGE_TASK_ENTITY_DESTROY	= 6
SPACE_STAGE_TASK_CUSTOM_TASK  	= 7
SPACE_STAGE_TASK_USE_ITEM		= 8
SPACE_STAGE_TASK_USE_TITLE		= 9

#------------------副本统计类型-------------------------
SPACE_STATISTICS_ENTRY_NONE				= 0
SPACE_STATISTICS_ENTRY_KILL_MONSTER		= 1
SPACE_STATISTICS_ENTRY_CONDITION_CHANGE = 3
SPACE_STATISTICS_ENTRY_GET_ITEM			= 4
SPACE_STATISTICS_ENTRY_COUNT_DOWN		= 5

#------------------副本策略点类型-----------------------
SPACE_STRATEGYPOINT_NONE   				= 0
SPACE_STRATEGYPOINT_ROLE_ADDBUFF		= 1
SPACE_STRATEGYPOINT_KILLMONSTER 		= 2
SPACE_STRATEGYPOINT_TRIGGER_BOX			= 3
SPACE_STRATEGYPOINT_MONSTER_HP_CHANGED 	= 4
SPACE_STRATEGYPOINT_ROLE_RECEIVEDAMAGE  = 5
SPACE_STRATEGYPOINT_TIME 				= 6

#------------------副本策略点归属类型-------------------
SPACE_STRATEGYPOINT_BELONG_NONE		= 0
SPACE_STRATEGYPOINT_BELONG_SPACE	= 1	#副本
SPACE_STRATEGYPOINT_BELONG_PERSON	= 2	#个人
SPACE_STRATEGYPOINT_BELONG_TEAM		= 3	#队伍

#-----------------副本策略点条件类型---------------------
SPACE_STRATEGYPOINT_CONDITION_NONE 			= 0
SPACE_STRATEGYPOINT_CONDITION_ROLE_ADDBUFF 	= 1
SPACE_STRATEGYPOINT_CONDITION_KILLMONSTER  	= 2

#-----------------副本策略点条件归属类型---------------------
SPACE_STRATEGYPOINT_CONDITION_BELONG_NONE		= 0
SPACE_STRATEGYPOINT_CONDITION_BELONG_SPACE		= 1	#副本
SPACE_STRATEGYPOINT_CONDITION_BELONG_PERSON		= 2	#个人
SPACE_STRATEGYPOINT_CONDITION_BELONG_TEAM		= 3	#队伍

#-----------------掉落类型--------------------------------
DROP_TYPE_DIRECT			=	1	#直接获得
DROP_TYPE_DROPBOX			=	2	#能过掉落箱子去拾取

#-----------------掉落数值类别----------------------------
DROP_VALUE_NOTHING			= "nothing" # 空
DROP_VALUE_MONEY				= "money"		# 金币
DROP_VALUE_EXP					= "exp"		# 经验
DROP_VALUE_XIUWEI			= "xiuwei"		# 修为
DROP_VALUE_POTENTIAL			= "potential"		# 潜能
DROP_VALUE_BANGGONG			= "tongContribute"		# 帮贡
DROP_VALUE_TONG_MONEY		= "tongMoney"	# 帮会资金
DROP_VALUE_FEATS				= "feats"		# 功勋
DROP_VALUE_MORALE				= "campMorale"	# 士气
DROP_VALUE_EXP_BL				= "exp_bl"	# 一倍基准经验
DROP_VALUE_POTENTIAL_BL		= "potential_bl"	# 一倍基准潜能
DROP_VALUE_XIUWEI_BL		= "xiuwei_bl"	# 一倍基准修为
DROP_VALUE_MONEY_BL			= "money_bl"	# 一倍基准金钱
DROP_VALUE_PSIONIC			= "psionic"	# 灵能
#-----------------掉落物品类别----------------------------
DROP_ITEM_DEFAULT			=	"item"	#普通物品类型


#组队物品拾取所有权范围
TEAM_ITEM_PICKUP_RANGE	= 150

#拾取物品掷骰子响应时间
ROLL_RANDOM_TIME		= 120

#掉落宝箱持续显示时间
DEOP_DESTROY_TIME = 120


#-----------------交易系统类别----------------------------
TRADE_GRID_NUM = 7			#交易面板格子数


#--------怪物所有权----------
#对应Monster表格中ownership字段(CST-3878)
MONSTER_OWNER_FIRST_DAMAGE = 0 	#首次攻击
MONSTER_OWNER_SHARE = 1 		#所有人共享
MONSTER_OWNER_NEVER_CHANGE = 2 	#不可变更


#-------------传送石相关-----------------------------------
TELEPORT_BY_TELEPORTSTONE = 0		#通过神行石传送
TELEPORT_BY_MONEY = 1				#通过消耗金钱传送
TELEPORT_BY_NONE = 2				#无条件(指消耗或神行石)传送

#--------------- 九字真言 ---------------------------------------
MONSTER_JZZY_ZY = 1		#真言
MONSTER_JZZY_XY = 2		#虚影
MONSTER_JZZY_DB = 3		#地板

MONSTER_JZZY_TYPE_LIN 	= 1	#临
MONSTER_JZZY_TYPE_BING 	= 2	#兵
MONSTER_JZZY_TYPE_DOU 	= 3	#斗
MONSTER_JZZY_TYPE_ZHE 	= 4	#者
MONSTER_JZZY_TYPE_JIE 	= 5	#皆
MONSTER_JZZY_TYPE_ZHEN 	= 6	#阵
MONSTER_JZZY_TYPE_LIE 	= 7	#列
MONSTER_JZZY_TYPE_QIAN 	= 8	#前
MONSTER_JZZY_TYPE_XING 	= 9	#行

MONSTER_JZZY_COMMOND_DICT = {
	MONSTER_JZZY_TYPE_LIN	: "LIN",
	MONSTER_JZZY_TYPE_BING	: "BING",
	MONSTER_JZZY_TYPE_DOU	: "DOU",
	MONSTER_JZZY_TYPE_ZHE	: "ZHE",
	MONSTER_JZZY_TYPE_JIE	: "JIE",
	MONSTER_JZZY_TYPE_ZHEN	: "ZHEN",
	MONSTER_JZZY_TYPE_LIE	: "LIE",
	MONSTER_JZZY_TYPE_QIAN	: "QIAN",
	MONSTER_JZZY_TYPE_XING	: "XING",
} 

#--------------- 练兵场 ---------------------------------------
LBC_SUCCESS_ADD_EXPLOIT = 600		# 练兵场成功获得军功
LBC_FAIL_ADD_EXPLOIT = 120			# 练兵场失败获得军功

ROLE_ADDBUFF_TYPE = [MONSTER_JZZY_TYPE_LIN, MONSTER_JZZY_TYPE_BING, MONSTER_JZZY_TYPE_DOU, MONSTER_JZZY_TYPE_ZHE, MONSTER_JZZY_TYPE_LIE, MONSTER_JZZY_TYPE_XING]
BOSS_ADDBUFF_TYPE = [MONSTER_JZZY_TYPE_LIN, MONSTER_JZZY_TYPE_DOU, MONSTER_JZZY_TYPE_ZHE, MONSTER_JZZY_TYPE_LIE, MONSTER_JZZY_TYPE_XING]
