# -*- coding: utf-8 -*-

import csdefine

#-------------------------------------------------------------------
#日志类型
#-------------------------------------------------------------------
LOG_TYPE_QUEST		= 1	#任务
LOG_TYPE_ITEM		= 2	#物品
LOG_TYPE_COIN		= 3	#货币
LOG_TYPE_PRO			= 4	#属性
LOG_TYPE_EQUIP		= 5	#装备
LOG_TYPE_RELATION	= 6	#人物关系
LOG_TYPE_PET			= 7	#幻兽
LOG_TYPE_TRADE		= 8	#交易
LOG_TYPE_MAIL		= 9	#邮件
LOG_TYPE_TONG		= 10	#帮会
LOG_TYPE_SKILL		= 11	#技能
LOG_TYPE_RECHARGE	= 12	#充值
LOG_TYPE_ACCOUNT	= 13	#账号
LOG_TYPE_ROLE		= 14	#角色
LOG_TYPE_VEND		= 15	#摆摊
LOG_TYPE_ACT_COPY		= 16	#活动、副本


#北京用到的新增的日志表
LOG_TYPE_ONLINE		= 17	#玩家在线数据
LOG_TYPE_COST		= 18	#消费表
LOG_TYPE_PROP		= 19	#道具
LOG_TYPE_ROLE_UP_LEVEL		= 20	#道具
LOG_TYPE_ACTIVE_RECORD		= 21	#活动记录
LOG_TYPE_ITEM_LOAD		= 22	#物品加载日志



#-----------------------------------
#任务日志分类
#-----------------------------------
LT_QUEST_ACCEPT		= 1	#接受任务
LT_QUEST_COMPLETE	= 2	#完成任务
LT_QUEST_ABANDON	= 3	#放弃任务

#-----------------------------------
#物品日志分类
#-----------------------------------
LT_ITEM_ADD			= 1	#添加物品
LT_ITEM_DEL			= 2	#删除物品
LT_ITEM_SET_AMOUNT	= 3	#设置数值
LT_ITEM_TRAN_STORE	= 4	#转入仓库
LT_ITEM_TALK_STORE	= 5	#取出仓库


#-----------------------------------
#货币日志分类
#-----------------------------------
LT_MONEY_CHANGE	= 1	#金钱改变
LT_XIANSHI_CHANGE	= 2	#仙石改变
LT_LINGSHI_CHANGE	= 3	#灵石改变
LT_XUANSHI_CHANGE	= 4	#玄石改变
LT_BINDMONEY_CHANGE	= 5	#绑定金钱改变

#-----------------------------------
#角色属性改变日志分类
#-----------------------------------
LT_PRO_EXP_CHANGE			= 1	#经验改变
LT_PRO_POTENTIAL_CHANGE	= 2	#潜能改变
LT_PRO_XIUWEI_ADD		= 3	#修为增长
LT_PRO_LEVEL_UPGRADE		= 4	#升级
LT_PRO_KILLING_CHANGE		= 5	#杀气改变
LT_PRO_CREDIT_CHANGE		= 6	#功勋值改变

#-----------------------------------
#角色装备日志分类
#-----------------------------------
LT_EQUIP_INTENSIFY	= 1	#装备强化
LT_EQUIP_COMPOSE	= 2	#装备打造
LT_EQUIP_SHUFFLE		= 3	#装备洗练
LT_EQUIP_SHUFFLE_REPLACE	= 4	#装备洗练替换
LT_EQUIP_RECAST		= 5	#装备重铸
LT_EQUIP_REPAIR		= 6	#装备修理
LT_EQUIP_BACKFIRE		= 7	#装备回火
LT_EQUIP_RESTORE		= 8	#装备还原
LT_EQUIP_SAVE			= 9	#装备保存
LT_EQUIP_TRAN_STAR	= 10	#装备传星
LT_EQUIP_OPEN_SAVE_SLOT		= 11 #开启强化保存栏位

#-----------------------------------
#角色装备日志分类
#-----------------------------------
LT_RELATION_TEACHER_BUILD		= 1	#建立师徒关系
LT_RELATION_TEACHER_REMOVE	= 2	#解除师徒关系

#-----------------------------------
#角色幻兽日志分类
#-----------------------------------
LT_PET_ADD			= 1	#获得幻兽
LT_PET_LOSE			= 2	#失去幻兽
LT_PET_SKILL_LEARN		= 3	#幻兽学习技能
LT_PET_SKILL_UPGRADE	= 4	#幻兽升级技能
LT_PET_SEAL			= 5	#幻兽封印
LT_PET_REPLACE_SKILL	= 6	#幻兽替换技能
LT_PET_COMPOSE		= 7	#幻兽合成
LT_PET_UP_STEP			= 8	#幻兽升阶

#打书技能类型
LT_PET_REPLACE_SKILL_ACTIVE	= 1 #主动技能
LT_PET_REPLACE_SKILL_PASSIVE	= 2 #被动技能

#-----------------------------------
#角色交易日志分类
#-----------------------------------
LT_TRADE_SWAP_ITEM		= 1	#与玩家交易物品
LT_TRADE_SWAP_MONEY	= 2	#与玩家交易金钱
LT_TRADE_SWAP_PET		= 3	#与玩家交易幻兽
LT_TRADE_NPC_BUY		= 4	#在NPC处买东西
LT_TRADE_NPC_SELL		= 5	#卖东西给NPC
LT_TRADE_SHOP_BUY		= 6	#在商城买东西
LT_TRADE_BUY_BACK		= 7	#回购
LT_TRADE_BUY_BACK_HIGH	= 8	#高价回购
LT_TRADE_RETURN_ITEM	= 9	#退货
LT_TRADE_GIVING_GOOD	= 10 #赠送

#-----------------------------
#角色交易方式
#-----------------------------
LT_TRADE_TYPE_TRANSFER		= 1	#直接交易
LT_TRADE_TYPE_VEND			= 2	#摆摊

#-----------------------------------
#邮件日志分类
#-----------------------------------
LT_MAIL_SEND		= 1	#发送邮件
LT_MAIL_READ		= 2	#阅读邮件
LT_MAIL_DEL		= 3	#删除邮件
LT_MAIL_EXTRACT	= 4	#提取邮件

#删除邮件分类
LT_MAIL_DEL_TYPE_ACTIVE			= 1 #主动删除
LT_MAIL_DEL_TYPE_TIME_ARRIVE	= 2 #时间达到
LT_MAIL_DEL_TYPE_BEREPLACED		= 3 #被其他新邮件顶替

#-----------------------------------
#帮会日志分类
#-----------------------------------
LT_TONG_CREATE				= 1	#帮会创建
LT_TONG_DISMISS				= 2	#帮会解散
LT_TONG_MEMBER_ADD		= 3	#成员加入
LT_TONG_MEMBER_LEAVE		= 4	#成员离开
LT_TONG_MONEY_CHANGE		= 5	#帮会资金改变
LT_TONG_LEVEl_CHANGE		= 6	#帮会等级改变
LT_TONG_GRADE_CHANGE		= 7	#帮会权限改变
LT_TONG_LEADER_CHANGE		= 8	#帮会帮主改变
LT_TONG_CONTRIBUTE_CHANGE  = 9	#帮会成员帮贡改变
LT_TONG_ITEM_ADD			= 10	#帮会物品添加
LT_TONG_ITEM_REMOVE		= 11	#帮会物品删除

#-----------------------------------
#技能日志分类
#-----------------------------------
LT_SKILL_LEARN		= 1	#学习技能
LT_SKILL_UPGRADE		= 2	#升级技能

#-----------------------------------
#账号日志分类
#-----------------------------------
LT_ACCOUNT_LOGON		= 1	#账号登录
LT_ACCOUNT_LOGOUT		= 2	#账号下线
LT_ACCOUNT_ROLE_ADD	= 3	#添加角色
LT_ACCOUNT_ROLE_DEL		= 4	#删除角色
LT_ACCOUNT_LOCK			= 5	#封锁账号
LT_ACCOUNT_UNLOCK		= 6	#解封账号


#-----------------------------------
#角色日志分类
#-----------------------------------
LT_ROLE_LOGON		= 1	#角色登录
LT_ROLE_LOGOUT		= 2	#角色下线
LT_ROLE_GAG			= 3	#角色禁言
LT_ROLE_UNGAG		= 4	#角色解除禁言
LT_ROLE_PRO_RECORD	= 5	#角色属性记录

#-----------------------------------
#充值类型日志分类
#-----------------------------------
LT_RECHARGE_GOLD	= 1
LT_RECHARGE_SILVER	= 2

#-----------------------------------
#活动、副本日志分类
#-----------------------------------
LT_ACT_COPY_TYPE_JOIN	= 1 #活动、副本参与


#-----------------------------------
#活动（副本）记录
#-----------------------------------
#活动奖励类型
ACTIVE_REWARD_TYPE_MONEY					= 1			# 金币奖励
ACTIVE_REWARD_TYPE_EXP						= 2			# 经验奖励
ACTIVE_REWARD_TYPE_ITEM						= 3			# 物品奖励
ACTIVE_REWARD_TYPE_SKILL					= 4			# 技能奖励
ACTIVE_REWARD_TYPE_XIUWEI					= 5			# 修为奖励
ACTIVE_REWARD_TYPE_POTENTIAL				= 6			# 潜能奖励
ACTIVE_REWARD_TYPE_TITLE					= 7			# 称号奖励
ACTIVE_REWARD_TYPE_CONTRIBUTE				= 8			# 帮贡奖励
ACTIVE_REWARD_TYPE_TONG_MONEY				= 9			# 帮会资金奖励
ACTIVE_REWARD_TYPE_BARRACKS_EXP				= 10		# 养兵经验奖励
ACTIVE_REWARD_TYPE_REWARD_ID				= 11		# 根据奖励ID奖励
ACTIVE_REWARD_TYPE_BIND_MONEY				= 12		# 绑金
ACTIVE_REWARD_TYPE_PSIONIC					= 13		# 灵能
ACTIVE_REWARD_TYPE_MAIL						= 14		# 邮件


ACTIVE_REWARD_TYPE_NAME = {
	ACTIVE_REWARD_TYPE_MONEY: "金币",
	ACTIVE_REWARD_TYPE_EXP: "经验",
	ACTIVE_REWARD_TYPE_ITEM: "物品",
	ACTIVE_REWARD_TYPE_SKILL: "技能",
	ACTIVE_REWARD_TYPE_XIUWEI: "修为",
	ACTIVE_REWARD_TYPE_POTENTIAL: "潜能",
	ACTIVE_REWARD_TYPE_TITLE: "称号",
	ACTIVE_REWARD_TYPE_CONTRIBUTE: "帮贡",
	ACTIVE_REWARD_TYPE_TONG_MONEY: "帮会资金",
	ACTIVE_REWARD_TYPE_BARRACKS_EXP: "养兵经验",
	ACTIVE_REWARD_TYPE_REWARD_ID: "根据奖励ID奖励",
	ACTIVE_REWARD_TYPE_BIND_MONEY: "绑金",
	ACTIVE_REWARD_TYPE_PSIONIC: "灵能",
	ACTIVE_REWARD_TYPE_MAIL: "邮件",
}

#环任务的奖励类型
LOOP_QUEST_REWARD_DICT = {
	csdefine.QUEST_REWARD_TYPE_MONEY: ACTIVE_REWARD_TYPE_MONEY,
	csdefine.QUEST_REWARD_TYPE_EXP: ACTIVE_REWARD_TYPE_EXP,
	#csdefine.QUEST_REWARD_TYPE_ITEM: ACTIVE_REWARD_TYPE_ITEM,
	csdefine.QUEST_REWARD_TYPE_SKILL: ACTIVE_REWARD_TYPE_SKILL,
	csdefine.QUEST_REWARD_TYPE_XIUWEI: ACTIVE_REWARD_TYPE_XIUWEI,
	csdefine.QUEST_REWARD_TYPE_POTENTIAL: ACTIVE_REWARD_TYPE_POTENTIAL,
	#csdefine.QUEST_REWARD_TYPE_ITEM_CHOOSE: ACTIVE_REWARD_TYPE_ITEM,
	csdefine.QUEST_REWARD_TYPE_TITLE: ACTIVE_REWARD_TYPE_TITLE,
	csdefine.QUEST_REWARD_TYPE_CONTRIBUTE: ACTIVE_REWARD_TYPE_CONTRIBUTE,
	csdefine.QUEST_REWARD_TYPE_TONG_MONEY: ACTIVE_REWARD_TYPE_TONG_MONEY,
	csdefine.QUEST_REWARD_TYPE_BARRACKS_EXP: ACTIVE_REWARD_TYPE_BARRACKS_EXP,
	csdefine.QUEST_REWARD_TYPE_REWARD_ID: ACTIVE_REWARD_TYPE_REWARD_ID,
}



#活动完成状态
ACTIVE_STATE_TYPE_SUCCESS = 1 #成功
ACTIVE_STATE_TYPE_FAIL = 2 #失败
ACTIVE_STATE_TYPE_ABANDON = 3 #放弃

#活动类型
ACTIVE_SPACE_TYPE_DEFAULT = 0 #未知
ACTIVE_SPACE_TYPE_BHLDZ = 1 #帮会掠夺战
ACTIVE_SPACE_TYPE_JWSJ = 2  #见闻拾记
ACTIVE_SPACE_TYPE_JSTK = 3  #晶石洞窟
ACTIVE_SPACE_TYPE_XBMJ = 4  #玄宝秘境
ACTIVE_SPACE_TYPE_LCJH = 5  #灵池净化
ACTIVE_SPACE_TYPE_WXHJ = 6  #五行画卷
ACTIVE_SPACE_TYPE_XMYY = 7 #消灭影妖
ACTIVE_SPACE_TYPE_XDGX = 8 #仙岛归墟
ACTIVE_SPACE_TYPE_HHMJ = 9  #火海秘境
ACTIVE_SPACE_TYPE_TZHJ = 10 #挑战虎蛟
ACTIVE_SPACE_TYPE_XTBL = 11 #玄天宝录
ACTIVE_SPACE_TYPE_PSBGZ = 12 #破碎八卦阵
ACTIVE_SPACE_TYPE_HQLZ = 13 #获取龙珠
ACTIVE_SPACE_TYPE_DFLDZ = 14 #洞府掠夺战
ACTIVE_SPACE_TYPE_DFZDZ = 15 #洞府争夺战
ACTIVE_SPACE_TYPE_LZG = 16 #雷泽谷
ACTIVE_SPACE_TYPE_FST = 17 #风煞坛
ACTIVE_SPACE_TYPE_TWG = 18 #天外宫
ACTIVE_SPACE_TYPE_JTLY = 19 #九天灵台
ACTIVE_SPACE_TYPE_HLG = 20 #浩灵谷
ACTIVE_SPACE_TYPE_BHMY = 21 #冰火灵脉
ACTIVE_SPACE_TYPE_LYZT = 22 #炼狱之塔
ACTIVE_SPACE_TYPE_QFGT = 23 #琴风古亭
ACTIVE_SPACE_TYPE_YLXF = 24 #云岚仙峰
ACTIVE_SPACE_TYPE_MDLX = 25 #密道历险
ACTIVE_SPACE_TYPE_BWK = 26 #宝物库
ACTIVE_SPACE_TYPE_LYSL = 27 #临渊试炼
ACTIVE_SPACE_TYPE_LYDF = 28 #灵岩洞府
ACTIVE_SPACE_TYPE_HDGC = 29 #荒岛古城
ACTIVE_SPACE_TYPE_GYMZ = 30 #鬼域迷阵
ACTIVE_SPACE_TYPE_DGSYZ = 31 #帝宫石印阵
ACTIVE_SPACE_TYPE_QXLG = 32 #青墟灵宫
ACTIVE_SPACE_TYPE_MQRSG = 33 #冥气人参果
ACTIVE_SPACE_TYPE_QQRYJ = 34 #巧取熔岩晶
ACTIVE_SPACE_TYPE_SFMJ = 35 #神风秘径
ACTIVE_SPACE_TYPE_LYSL = 36 #雷域试炼
ACTIVE_SPACE_TYPE_CYXG = 37 #穿越峡谷
ACTIVE_SPACE_TYPE_MXSJ = 38 #魔像水晶
ACTIVE_SPACE_TYPE_KNCZ = 39 #狂牛冲撞
ACTIVE_SPACE_TYPE_XYHY = 40 #仙隐画院
ACTIVE_SPACE_TYPE_YCJMD_JINZHAN = 41 #勇闯绝命岛（近战）
ACTIVE_SPACE_TYPE_YCJMD_SHOOT = 42 #勇闯绝命岛（远程）
ACTIVE_SPACE_TYPE_GCZ = 43 # 攻城战
ACTIVE_SPACE_TYPE_HLTC1 = 44 # 幻莲天池
ACTIVE_SPACE_TYPE_HLTC2 = 45 # 幻莲天池（单人）
ACTIVE_SPACE_TYPE_LCZ 	= 46 # 雷池阵
ACTIVE_SPACE_TYPE_TCDL 	= 47 # 逃出丹炉
ACTIVE_SPACE_TYPE_ZFZL 	= 48 # 逐风之路

#活动对应名称
ACTIVE_SPACE_NAME_DICT = {
	ACTIVE_SPACE_TYPE_BHLDZ: "帮会掠夺战",
	ACTIVE_SPACE_TYPE_JWSJ: "见闻拾记",
	ACTIVE_SPACE_TYPE_JSTK: "琉璃洞窟",
	ACTIVE_SPACE_TYPE_XBMJ: "玄宝秘境",
	ACTIVE_SPACE_TYPE_LCJH: "灵池净化",
	ACTIVE_SPACE_TYPE_WXHJ: "五行画卷",
	ACTIVE_SPACE_TYPE_XMYY: "消灭影妖",
	ACTIVE_SPACE_TYPE_XDGX: "仙岛归墟",
	ACTIVE_SPACE_TYPE_HHMJ: "火海秘境",
	ACTIVE_SPACE_TYPE_TZHJ: "挑战虎蛟",
	ACTIVE_SPACE_TYPE_XTBL: "玄天宝录",
	ACTIVE_SPACE_TYPE_PSBGZ: "破碎八卦阵",
	ACTIVE_SPACE_TYPE_HQLZ: "获取龙珠",
	ACTIVE_SPACE_TYPE_DFLDZ: "洞府掠夺战",
	ACTIVE_SPACE_TYPE_DFZDZ: "洞府争夺战",
	ACTIVE_SPACE_TYPE_LZG: "雷泽谷",
	ACTIVE_SPACE_TYPE_FST: "风煞坛",
	ACTIVE_SPACE_TYPE_TWG: "天外宫",
	ACTIVE_SPACE_TYPE_JTLY: "九天灵台",
	ACTIVE_SPACE_TYPE_HLG : "浩灵谷",
	ACTIVE_SPACE_TYPE_BHMY : "冰火灵脉",
	ACTIVE_SPACE_TYPE_LYZT : "炼狱之塔",
	ACTIVE_SPACE_TYPE_QFGT : "琴风古亭",
	ACTIVE_SPACE_TYPE_YLXF : "云岚仙峰",
	ACTIVE_SPACE_TYPE_MDLX : "密道历险",
	ACTIVE_SPACE_TYPE_BWK : "宝物库",
	ACTIVE_SPACE_TYPE_LYSL : "临渊试炼",
	ACTIVE_SPACE_TYPE_LYDF : "灵岩洞府",
	ACTIVE_SPACE_TYPE_HDGC : "荒岛古城",
	ACTIVE_SPACE_TYPE_GYMZ : "鬼域迷阵",
	ACTIVE_SPACE_TYPE_DGSYZ : "帝宫石印阵",
	ACTIVE_SPACE_TYPE_QXLG : "青墟灵宫",
	ACTIVE_SPACE_TYPE_MQRSG : "冥气人参果",
	ACTIVE_SPACE_TYPE_QQRYJ : "巧取熔岩晶",
	ACTIVE_SPACE_TYPE_SFMJ : "神风秘径",
	ACTIVE_SPACE_TYPE_LYSL : "雷域试炼",
	ACTIVE_SPACE_TYPE_CYXG : "穿越峡谷",
	ACTIVE_SPACE_TYPE_MXSJ : "魔像水晶",
	ACTIVE_SPACE_TYPE_KNCZ : "狂牛冲撞",
	ACTIVE_SPACE_TYPE_XYHY : "仙隐画院",
	ACTIVE_SPACE_TYPE_XYHY : "仙隐画",
	ACTIVE_SPACE_TYPE_YCJMD_JINZHAN : "勇闯绝命岛（近战）",
	ACTIVE_SPACE_TYPE_YCJMD_SHOOT : "勇闯绝命岛（远程）",
	ACTIVE_SPACE_TYPE_GCZ: "攻城战",
	ACTIVE_SPACE_TYPE_HLTC1: "幻莲天池",
	ACTIVE_SPACE_TYPE_HLTC2: "幻莲天池(单人)",
	ACTIVE_SPACE_TYPE_LCZ: "雷池阵",
	ACTIVE_SPACE_TYPE_TCDL: "逃出丹炉",
	ACTIVE_SPACE_TYPE_ZFZL: "逐风之路",
}

#SpaceScriptID对应活动
ACTIVE_SPACE_SCRIPT_ID_DICT = {
	"fu_ben_L_BHLD_GJJD": ACTIVE_SPACE_TYPE_BHLDZ,
	"cycle_L_JSDK": ACTIVE_SPACE_TYPE_JSTK,
	"L_TZHJ": ACTIVE_SPACE_TYPE_XBMJ, #环任务
	"cycle_L_FHJN": ACTIVE_SPACE_TYPE_LCJH,
	"cycle_L_WXHJ": ACTIVE_SPACE_TYPE_WXHJ,
	"cycle_L_XMYY": ACTIVE_SPACE_TYPE_XMYY,
	"cycle_L_XDGX": ACTIVE_SPACE_TYPE_XDGX,
	"cycle_L_HHMJ": ACTIVE_SPACE_TYPE_HHMJ,
	"L_WSS_Planes201": ACTIVE_SPACE_TYPE_TZHJ,
	"cycle_L_XTBL": ACTIVE_SPACE_TYPE_XTBL,
	"cycle_L_PSDBGZ": ACTIVE_SPACE_TYPE_PSBGZ,
	"cycle_L_HQLZ": ACTIVE_SPACE_TYPE_HQLZ,
	"L_LHMJDF": ACTIVE_SPACE_TYPE_DFLDZ,
	"fu_ben_L_LZG":ACTIVE_SPACE_TYPE_LZG,
	"fu_ben_L_FST":ACTIVE_SPACE_TYPE_FST,
	"fu_ben_L_JTLY_SC" : ACTIVE_SPACE_TYPE_TWG,
	"fu_ben_L_JTLY_XC":ACTIVE_SPACE_TYPE_JTLY,
	"fu_ben_L_HLG" : ACTIVE_SPACE_TYPE_HLG,
	"fu_ben_L_BHMY" : ACTIVE_SPACE_TYPE_BHMY,
	"fu_ben_L_LYZT" : ACTIVE_SPACE_TYPE_LYZT,
	"fu_ben_L_QFGT"  : ACTIVE_SPACE_TYPE_QFGT,
	"fu_ben_L_HZMG_YLXF" : ACTIVE_SPACE_TYPE_YLXF,
	"fu_ben_L_MDLX" : ACTIVE_SPACE_TYPE_MDLX,
	"fu_ben_L_HZMG_BWK" : ACTIVE_SPACE_TYPE_BWK,
	"fu_ben_L_LYSL" : ACTIVE_SPACE_TYPE_LYSL,
	"fu_ben_L_WFSZ" : ACTIVE_SPACE_TYPE_LYDF,
	"fu_ben_L_HZMG_JSGC" : ACTIVE_SPACE_TYPE_HDGC,
	"fu_ben_L_GYMZ" : ACTIVE_SPACE_TYPE_GYMZ,
	"fu_ben_L_DGSYZ" : ACTIVE_SPACE_TYPE_DGSYZ,
	"cycle_L_LQMG" : ACTIVE_SPACE_TYPE_QXLG,
	"cycle_L_MQRSG" : ACTIVE_SPACE_TYPE_MQRSG,
	"cycle_L_QQRYJ" : ACTIVE_SPACE_TYPE_QQRYJ,
	"L_SFMJ" : ACTIVE_SPACE_TYPE_SFMJ,
	"cycle_L_LYSL" : ACTIVE_SPACE_TYPE_LYSL,
	"L_XG_01" : ACTIVE_SPACE_TYPE_CYXG,
	"cycle_L_MXSJ" : ACTIVE_SPACE_TYPE_MXSJ,
	"cycle_L_KNCZ" : ACTIVE_SPACE_TYPE_KNCZ,
	"fu_ben_L_XYHY" : ACTIVE_SPACE_TYPE_XYHY,
	"fu_ben_L_YCJMD_tuanben" : ACTIVE_SPACE_TYPE_YCJMD_JINZHAN,
	"fu_ben_L_YCJMD" : ACTIVE_SPACE_TYPE_YCJMD_SHOOT,
	"fu_ben_L_GCZ": ACTIVE_SPACE_TYPE_GCZ,
	"fu_ben_L_HLTC1" : ACTIVE_SPACE_TYPE_HLTC1,
	"fu_ben_L_HLTC2" : ACTIVE_SPACE_TYPE_HLTC2,
	"fu_ben_L_LCZ_1" : ACTIVE_SPACE_TYPE_LCZ,
	"fu_ben_L_TCDL" : ACTIVE_SPACE_TYPE_TCDL,
	"L_FMNL_Planes201" : ACTIVE_SPACE_TYPE_ZFZL,
}